routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

//site

Route::post('homeBusca','homeController@homeBusca')->name('homeBusca');
Route::post('homePedir','homeController@homePedir')->name('homePedir');
Route::get("/", "homeController@index")->name('home.index');
Route::get('home_detalhes/{id}', 'homeController@detalhes');
Route::get('/home', 'HomeController@index')->name('home');

Route::get('/admin', function() {
    return view('admin.index');
})->middleware('auth');

Route::prefix('admin')->group(function () {
    
    Route::resource('pratos', 'Admin\PratoController')->middleware('auth');
    Route::resource('pedidos', 'Admin\PedidoController')->middleware('auth');
    Route::resource('tipos', 'Admin\TipoController')->middleware('auth');
    Route::get('/grafpratos', 'Admin\PedidoController@grafico')->middleware('auth');
    Route::get('pedidos_email/{id}', 'Admin\PedidoController@email')
->name('pedidos.email')->middleware('auth');
Route::get('/relpratos', 'Admin\PedidoController@relatorio');
Route::get('/relpedidos', 'Admin\PedidoController@relpedidos');
    
    
    
});

Auth::routes();

resources/views/admin/index.blade.php
@extends('adminlte::page')

@section('title', 'Delivery Avenida')

@section('content_header')
    <h1>Página Principal</h1>


@stop

@section('content')
    <H4>Bem-Vindo {{ Auth::user()->name }}!</h4>
    <p>Área de Administração do Site Avenida</p>
@stop

resources/views/admin/pedidos_list.blade.php
@extends('adminlte::page')

@section('title', 'Lista de Pedidos')

@section('content_header')
    
@stop

@section('content')

@if (session('status'))
   <div class="alert alert-success">
      {{ session('status') }}
   </div> 
@endif

<table class="table table-striped">
  <thead>
    <tr>
    <th>Nº</th>
      <th>Nome</th>
      <th>Endereço</th>
      <th>Telefone</th>
      <th>Prato</th>
      <th>Email</th>     
      <th>Valor</th>     
      <th>Data</th>
      <th>Enviar</th>
    </tr>
  </thead>
  <tbody>
    @forelse ($pedidos as $p)
      <tr>
        <td> {{$p->id}} </td>
        <td> {{$p->nome}} </td>
        <td> {{$p->endereco}} </td>
        <td> {{$p->telefone}} </td>
        <td> {{$p->prato}} </td>
        <td> {{$p->email}} </td>
        <td> R$: {{number_format($p->preco, 2, ',', '.')}} </td>
        <td> {{($p->created_at)}} </td>
        
        
        <td><a href="{{ route('pedidos.email', $p->id) }}" 
          class="btn btn-primary btn-sm" role="button">Email</a>&nbsp;</td>
        
         
            
               
                  
                   {{csrf_field()}}
                  
            </form>
        </td>
        @if ($loop->iteration == $loop->count)
        <tr><td colspan=8><p>Soma dos Pedidos R$: 
                               {{number_format($soma, 2, ',', '.')}}</p>
                               <p>Nº de Pedidos Cadastrados: {{$numPedidos}} </p>                             
                              </td></tr>
        @endif        
    @empty
      <tr><td colspan=8> Não há pedidos cadastrados ou 
                         para o filtro informado </td></tr>
    @endforelse

  </tbody>
</table>  

{{ $pedidos->links() }}
@stop

resources/views/admin/pedidos_rel.blade.php
<<div class="container-fluid">
 <h1 style="text-align: center">Delivery Avenida</h1>
 <h3 style="text-align: center">Relatório de Pedidos</h3>
<table class="table table-bordered table-sm">
 <thead class="thead-light">
 <tr>
 <th>Data:</th><th>Pedido N°:   </th><th>Nome:</th><th>Cód. Prato:</th><th>Valor:</th>
 </tr>
 </thead>
 

 <tbody>

    @foreach ($pedidos as $p)
    <tr>
    <td> {{date_format($p->created_at, 'd/m/Y H:m')}} </td>
      <td> {{ $p->id }} </td>
      <td> {{ $p->nome }} </td>
      <td> {{ $p->prato_id}} </td>
      <td> R$: {{number_format($p->preco, 2, ',', '.')}}</td>

      </tbody>          
               
      {{csrf_field()}}
                  
                  </form>
              </td>
              @if ($loop->iteration == $loop->count)
              <tr><td colspan=8><p>Soma dos Pedidos R$: 
                                     {{number_format($soma, 2, ',', '.')}}
                                     <p>Nº de Pedidos Cadastrados: {{$numPedidos}} </p>                             
                                    </td></tr>
              @endif        
         
       
                                     </tr>

@endforeach

</tbody>
</table>

resources/views/admin/pratos_form.blade.php
@extends('adminlte::page')

@section('title', 'Cadastro de Pratos')

@section('content_header')
 
    @if ($acao==1)
       <h2>Inclusão de Pratos
    @elseif ($acao ==2)
       <h2>Alteração de Pratos
    @endif          

    <a href="{{ route('pratos.index') }}" class="btn btn-primary pull-right"
       role="button">Voltar</a>
    </h2>

@endsection

@section('content')

   <div class="container-fluid">

    @if ($acao==1)
      <form method="POST" action="{{ route('pratos.store') }}" enctype="multipart/form-data">
    @elseif ($acao==2)
      <form method="POST" action="{{route('pratos.update', $reg->id)}}" enctype="multipart/form-data">
      {!! method_field('put') !!}
    @endif          
    {{ csrf_field() }}

    <div class="row">
      <div class="col-sm-6">
        <div class="form-group">
          <label for="nome">Nome do Prato</label>
          <input type="text" id="nome" name="nome" required 
                 value="{{$reg->nome or old('nome')}}"
                 class="form-control">
        </div>
      </div>

      <div class="col-sm-6">
        <div class="form-group">
          <label for="tipo_id">Tipo do Prato</label>
          <select id="tipo_id" name="tipo_id" class="form-control">
            @foreach($tipos as $t)
              <option value="{{$t->id}}" 
                      {{ ((isset($reg) and $reg->tipo_id == $t->id) or 
                         old('tipo_id') == $t->id) ? "selected" : "" }}>
                      {{$t->nome}}</option>
            @endforeach
          </select>  
        </div>
      </div>
    </div>              

    
      
        <div class="col-sm-6">
          <div class="form-group">
              <label for="preco">Preço R$</label>
              <input type="text" id="preco" name="preco" required 
                     value="{{$reg->preco or old('preco')}}"
                     class="form-control">
          </div>
        </div>
    </div>

    <div class="row">
        <div class="col-sm-4">
          <div class="form-group">
            <label for="ano">Descrição</label>
            <input type="text" id="descricao" name="descricao" required 
                   value="{{$reg->descricao or old('descricao')}}"
                   class="form-control">
          </div>
        </div>
      
       

        <div class="col-sm-4">
          <div class="form-group">
            <label for="foto">Foto</label>
            <input type="file" id="foto" name="foto" required
                   class="form-control">
          </div>
        </div>
        
    </div>

    <input type="submit" value="Enviar" class="btn btn-success">
    <input type="reset" value="Limpar" class="btn btn-warning">

    </form>
  </div>

@endsection

@section('js')
  <script src="https://code.jquery.com/jquery-latest.min.js"></script>
  <script src="/js/jquery.mask.min.js"></script>

  <script>
    $(document).ready(function() {
      $('#preco').mask('#.###.##0,00', {reverse: true});
    });
  </script>  
@endsection
@section('content')

@if ($errors->any())
    <div class="alert alert-danger">
        <ul>
            @foreach ($errors->all() as $error)
                <li>{{ $error }}</li>
            @endforeach
        </ul>
    </div>
@endif

resources/views/admin/pratos_graf.blade.php
@extends('adminlte::page')

@section('title', 'Gráfico de Pedidos')

@section('content_header')
    <h1>Gráfico dos Pedidos
    <a href="{{ route('pedidos.index') }}" class="btn btn-primary pull-right"
       role="button">Listagem</a>
    </h1>
@endsection

@section('content')

<script type="text/javascript" src="https://www.gstatic.com/charts/loader.js"></script>
    <script type="text/javascript">
      google.charts.load("current", {packages:["corechart"]});
      google.charts.setOnLoadCallback(drawChart);
     
     
      function drawChart() {
 var data = google.visualization.arrayToDataTable([['Nome', 'Pedidos'],
 
 @foreach ($totais as $total)
 {!! "['$total->nome', $total->total]," !!}
 @endforeach
 ]);
 var options = {
 title: 'Número de Pedidos por Prato',
 is3D: true,
 };
 var chart = new google.visualization
 .PieChart(document.getElementById('piechart_3d'));
 chart.draw(data, options);
 }
</script>
<div id="piechart_3d" style="width: 900px; height: 500px;"></div>

@endsection

resources/views/admin/pratos_list.blade.php
@extends('adminlte::page')

@section('title', 'Cadastro de Pratos')

@section('content_header')
    <h1>Cadastro de Pratos
    <a href="{{ route('pratos.create') }}" class="btn btn-primary pull-right"
       role="button">Novo</a>
    </h1>
@stop

@section('content')

@if (session('status'))
   <div class="alert alert-success">
      {{ session('status') }}
   </div> 
@endif

<table class="table table-striped">
  <thead>
    <tr>
      <th>Nome</th>
      <th>Tipo</th>
      <th>Descrição</th>
      <th>Preço R$</th>     
      <th>Foto</th>
      <th>Ações</th>
    </tr>
  </thead>
  <tbody>
    @forelse ($pratos as $p)
      <tr>
        <td> {{$p->nome}} </td>
        <td> {{$p->tipo->nome}} </td>
        <td> {{$p->descricao}} </td>
        <td> {{number_format($p->preco, 2, ',', '.')}} </td>
        <td>
          @if (Storage::exists($p->foto))
            <img src="{{url('storage/'.$p->foto)}}" 
                 style="width: 100px; height: 60px" alt="Foto">
          @else
            <img src="{{url('storage/fotos/semfoto.png')}}" 
                 style="width: 100px; height: 60px" alt="Foto">
         @endif
        </td>
        <td> 
            <a href="{{route('pratos.edit', $p->id)}}" 
                class="btn btn-warning btn-sm" title="Alterar"
                role="button"><i class="fa fa-edit"></i></a> &nbsp;&nbsp;
            <form style="display: inline-block"
                  method="post"
                  action="{{route('pratos.destroy', $p->id)}}"
                  onsubmit="return confirm('Confirma Exclusão?')">
                   {{method_field('delete')}}
                   {{csrf_field()}}
                  <button type="submit" title="Excluir"
                          class="btn btn-danger btn-sm"><i class="far fa-trash-alt"></i></button>
            </form>
        </td>
        @if ($loop->iteration == $loop->count)
             <tr><td colspan=8>Total dos Pratos cadastrados: {{$numPratos}}                              
                              </td></tr>
        @endif        
    @empty
      <tr><td colspan=8> Não há pratos cadastrados ou 
                         para o filtro informado </td></tr>
    @endforelse

  </tbody>
</table>  

{{ $pratos->links() }}
@stop

@section('js')
  <script defer src="https://use.fontawesome.com/releases/v5.0.10/js/all.js" integrity="sha384-slN8GvtUJGnv6ca26v8EzVaR9DC58QEwsIk9q1QXdCU8Yu8ck/tL/5szYlBbqmS+" crossorigin="anonymous"></script>
@endsection

resources/views/admin/pratos_rel.blade.php
<<div class="container-fluid">
 <h1 style="text-align: center">Cardápio Delivery Avenida</h1>
 <h5 style="text-align: center">Lista de Pratos Cadastrados</h5>
<table class="table table-bordered table-sm">
 <thead class="thead-light">
 <tr>
 <th>Numero</th><th>Nome</th><th>Tipo de Prato</th><th>Descrição</th><th>Preço</th><th>Foto</th>
 </tr>
 </thead>
 

 <tbody>

    @foreach ($pratos as $prato)
    <tr>
      <td> {{ $prato->id }} </td>
      <td> {{ $prato->nome }} </td>
      <td> {{ $prato->tipo->nome }} </td>
      <td> {{ $prato->descricao }} </td>
      <td> R$: {{number_format($prato->preco, 2, ',', '.')}} </td>
      <td> <img src='storage/{{ $prato->foto }}' style='width: 120px; height: 80px;'> </td>
      
     
    </tr>

    @endforeach

  </tbody>
</table>

resources/views/admin/tipos_form.blade.php
@extends('adminlte::page')

@section('title', 'Cadastro de Tipos')

@section('content_header')
 
    @if ($acao==1)
       <h2>Inclusão de Tipos
    @elseif ($acao ==2)
       <h2>Alteração de Tipos
    @endif          

    <a href="{{ route('tipos.index') }}" class="btn btn-primary pull-right"
       role="button">Voltar</a>
    </h2>

@endsection

@section('content')

   <div class="container-fluid">

    @if ($acao==1)
      <form method="POST" action="{{ route('tipos.store') }}" enctype="multipart/form-data">
    @elseif ($acao==2)
      <form method="POST" action="{{route('tipos.update', $reg->id)}}" enctype="multipart/form-data">
      {!! method_field('put') !!}
    @endif          
    {{ csrf_field() }}

    <div class="row">
      <div class="col-sm-6">
        <div class="form-group">
          <label for="nome">Nome do Tipo de Prato</label>
          <input type="text" id="nome" name="nome" required 
                 value="{{$reg->nome or old('nome')}}"
                 class="form-control">
        </div>
      </div>

      
    </div>              

    
      
      

    <div class="row">
        <div class="col-sm-4">
          <div class="form-group">
            <label for="ano">Descrição</label>
            <input type="text" id="descricao" name="descricao" required 
                   value="{{$reg->descricao or old('descricao')}}"
                   class="form-control">
          </div>
        </div>
      
       

        
    </div>

    <input type="submit" value="Enviar" class="btn btn-success">
    <input type="reset" value="Limpar" class="btn btn-warning">

    </form>
  </div>

@endsection

@section('js')
  <script src="https://code.jquery.com/jquery-latest.min.js"></script>
  <script src="/js/jquery.mask.min.js"></script>

  
@endsection

resources/views/admin/tipos_list.blade.php
@extends('adminlte::page')

@section('title', 'Cadastro de Tipos')

@section('content_header')
    <h1>Cadastro de Tipos
    <a href="{{ route('tipos.create') }}" class="btn btn-primary pull-right"
       role="button">Novo</a>
    </h1>
@stop

@section('content')

@if (session('status'))
   <div class="alert alert-success">
      {{ session('status') }}
   </div> 
@endif

<table class="table table-striped">
  <thead>
    <tr>
      <th>Nome</th>
      <th>Descrição</th>
      <th>Ações</th>
    </tr>
  </thead>
  <tbody>
    @forelse ($tipos as $t)
      <tr>
        <td> {{$t->nome}} </td>
        <td> {{$t->descricao}} </td>
        <td> {{date_format($t->created_at, 'd/m/Y')}} </td>
        <td> 
            <a href="{{route('tipos.edit', $t->id)}}" 
                class="btn btn-warning btn-sm" title="Alterar"
                role="button"><i class="fa fa-edit"></i></a> &nbsp;&nbsp;
            <form style="display: inline-block"
                  method="post"
                  action="{{route('tipos.destroy', $t->id)}}"
                  onsubmit="return confirm('Confirma Exclusão?')">
                   {{method_field('delete')}}
                   {{csrf_field()}}
                  <button type="submit" title="Excluir"
                          class="btn btn-danger btn-sm"><i class="far fa-trash-alt"></i></button>
            </form>
        </td>
      
    @empty
      <tr><td colspan=8> Não há tipos cadastrados ou 
                         para o filtro informado </td></tr>
    @endforelse

  </tbody>
</table>  

{{ $tipos->links() }}
@stop

@section('js')
  <script defer src="https://use.fontawesome.com/releases/v5.0.10/js/all.js" integrity="sha384-slN8GvtUJGnv6ca26v8EzVaR9DC58QEwsIk9q1QXdCU8Yu8ck/tL/5szYlBbqmS+" crossorigin="anonymous"></script>
@endsection